"""empty message

Revision ID: 74a331c948d6
Revises: 
Create Date: 2022-07-27 14:22:40.655169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74a331c948d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("''"))
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['state_id'])
    op.alter_column('state', 'state_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state', 'state_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'lga', type_='foreignkey')
    op.alter_column('lga', 'lga_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('lga', 'state_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
