"""empty message

Revision ID: 88aeef10289f
Revises: c3c296380442
Create Date: 2022-07-27 14:31:18.400603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88aeef10289f'
down_revision = 'c3c296380442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'lga', 'state', ['state_id'], ['state_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lga', type_='foreignkey')
    # ### end Alembic commands ###
